apt install python3-pip python3.13-venv --no-install-recommends -y

mkdir -p /opt/python/crowdsec_abuse_reporter
cd /opt/python/crowdsec_abuse_reporter
python3 -m venv /opt/python/crowdsec_abuse_reporter/.venv  
source /opt/python/crowdsec_abuse_reporter/.venv/bin/activate

pip install --upgrade pip
pip install --group $(cd /opt/crowdsec-toolbox/crowdsec-abuse-reporter && pwd)/pyproject.toml:default

# Docker Build
PROJECT="crowdsec-abuse-reporter" && \
cd /opt/crowdsec-toolbox && \
VERSION="$(python3 -c 'import tomllib; print(tomllib.load(open("crowdsec-abuse-reporter/pyproject.toml", "rb"))["project"]["version"])')" && \
GIT_SHA="$(git rev-parse --verify HEAD)" && \
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)" && \
printf 'APP_VERSION=%s\nGIT_SHA=%s\nBUILD_DATE=%s\n' "$VERSION" "$GIT_SHA" "$BUILD_DATE" > "${PROJECT}/BUILD_INFO" && \
docker buildx build \
  --platform linux/amd64 \
  --pull \
  -f "${PROJECT}/docker/Dockerfile" \
  --build-arg APP_VERSION="$VERSION" \
  --build-arg GIT_SHA="$GIT_SHA" \
  --build-arg BUILD_DATE="$BUILD_DATE" \
  -t "docker.cirrio.de/${PROJECT}:latest" \
  --push .

# Get API credentials from CrowdSec
docker exec -it crowdsec cat /etc/crowdsec/local_api_credentials.yaml

docker compose down && docker compose pull && docker compose up -d
